(ns bdocgen.site
  (:require [clojure.string :as str]))

(defn page-title
  [scope]
  (case scope
    :project "BDocGen Project Documentation"
    "BDocGen Self Documentation"))

(defn render-index-html
  [plan]
  (let [title (page-title (:scope plan))
        items (if (seq (:doc-paths plan))
                (str/join ""
                          (map (fn [path]
                                 (str "<li><code>" path "</code></li>"))
                               (:doc-paths plan)))
                "<li><em>No markdown docs discovered.</em></li>")]
    (str "<!doctype html>\n"
         "<html lang=\"en\">\n"
         "<head>\n"
         "  <meta charset=\"utf-8\">\n"
         "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
         "  <title>" title "</title>\n"
         "  <style>\n"
         "    body { font-family: ui-sans-serif, sans-serif; margin: 2rem; line-height: 1.5; }\n"
         "    main { max-width: 900px; margin: 0 auto; }\n"
         "    code { background: #f3f4f6; padding: 0.1rem 0.3rem; border-radius: 0.25rem; }\n"
         "  </style>\n"
         "</head>\n"
         "<body>\n"
         "<main>\n"
         "  <h1>" title "</h1>\n"
         "  <p>This is a bootstrap output generated by BDocGen.</p>\n"
         "  <p>Scope: <strong>" (name (:scope plan)) "</strong></p>\n"
         "  <p>Discovered markdown files: <strong>" (:doc-count plan) "</strong></p>\n"
         "  <h2>Discovered Sources</h2>\n"
         "  <ul>" items "</ul>\n"
         "</main>\n"
         "</body>\n"
         "</html>\n")))
