when:
  event: [push]
matrix:
  LISP:
    - ccl
    - clasp
    - clisp
    - ecl
    - sbcl
steps:
  run:
    image: shinmera/parachute:latest
    pull: true
    settings:
      systems: float-features/tests
      implementation: ${LISP}
