(in-package :bdocgen)

(defun parse-cli-args (argv)
  (labels ((next-value (list key)
             (if (null list)
                 (error "Missing value for ~a" key)
                 (values (first list) (rest list)))))
    (let ((scope "project")
          (project-root ".")
          (docs-root "docs")
          (output-dir nil)
          (output-dir-explicit nil)
          (pages-target "github")
          (theme-source "css")
          (scss-entry "tools/bdocgen/theme/main.scss")
          (scss-style "expanded")
          (addon-name ""))
      (loop while argv
            do (let ((key (first argv)))
                 (setf argv (rest argv))
                 (cond
                   ((string= key "--scope")
                    (multiple-value-setq (scope argv) (next-value argv key)))
                   ((string= key "--project-root")
                    (multiple-value-setq (project-root argv) (next-value argv key)))
                   ((string= key "--docs-root")
                    (multiple-value-setq (docs-root argv) (next-value argv key)))
                   ((string= key "--output-dir")
                    (multiple-value-setq (output-dir argv) (next-value argv key))
                    (setf output-dir-explicit t))
                   ((string= key "--pages-target")
                    (multiple-value-setq (pages-target argv) (next-value argv key)))
                   ((string= key "--theme-source")
                    (multiple-value-setq (theme-source argv) (next-value argv key)))
                   ((string= key "--scss-entry")
                    (multiple-value-setq (scss-entry argv) (next-value argv key)))
                   ((string= key "--scss-style")
                    (multiple-value-setq (scss-style argv) (next-value argv key)))
                   ((string= key "--addon-name")
                    (multiple-value-setq (addon-name argv) (next-value argv key)))
                   (t (error "Unknown argument: ~a" key)))))
      (let ((normalized-target (normalize-pages-target pages-target)))
        (unless (member (string-downcase theme-source) '("css" "scss") :test #'string=)
          (error "Unsupported --theme-source: ~a (expected css|scss)" theme-source))
        (unless (member (string-downcase scss-style) '("expanded" "compressed") :test #'string=)
          (error "Unsupported --scss-style: ~a (expected expanded|compressed)" scss-style))
        (unless output-dir-explicit
          (setf output-dir (default-output-dir-for-pages-target normalized-target)))
        (list :scope scope
              :project-root project-root
              :docs-root docs-root
              :output-dir output-dir
              :pages-target normalized-target
              :theme-source (string-downcase theme-source)
              :scss-entry scss-entry
              :scss-style (string-downcase scss-style)
              :addon-name addon-name)))))

(defun print-result (result)
  (format t "BDocGen status: ~a~%" (getf result :status))
  (format t "BDocGen scope: ~a~%" (getf result :scope))
  (format t "BDocGen pages target: ~a~%" (getf result :pages-target "github"))
  (format t "BDocGen theme source: ~a~%" (getf result :theme-source "css"))
  (format t "BDocGen pages: ~a~%" (getf result :page-count))
  (format t "index: ~a~%" (getf result :index-path))
  (format t "manifest: ~a~%" (getf result :manifest-path)))

(defun main ()
  (handler-case
      (let* ((argv (uiop:command-line-arguments))
             (config (parse-cli-args argv))
             (result (build-site config)))
        (print-result result)
        0)
    (error (condition)
      (format *error-output* "BDocGen error: ~a~%" condition)
      1)))
